### ISSUE TITLE
JSON: unexpected token <

### ISSUE THREAD

**Issue by vMarkus** [apnex/vmw-cli#3]
during index of several groups like vsphere or vrealize suite the same error shows on each product:

`Offering up afforementioned snacks as a sacrifice to [https://my.vmware.com/oam/server/auth_cred_submit]
Pulling landing index.json [https://my.vmware.com/group/vmware/downloads]
undefined:57
		<!DOCTYPE html>
		^

SyntaxError: Unexpected token < in JSON at position 58
    at JSON.parse (<anonymous>)
    at Request.self.request.get [as _callback] (/usr/local/lib/node_modules/vmw-cli/lib/get-index.js:62:18)
    at Request.self.callback (/usr/local/lib/node_modules/vmw-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/vmw-cli/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/vmw-cli/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
`

Not able to index any product or group

**Comment by vMarkus** [comment]
ok, found my issue: typo at password - sorry!

- Pulling landing index.json [https://my.vmware.com/group/vmware/downloads]
- Resolving files in solution [vmware-workstation-player]
instead of unexpected token is what is happening next before indexing starts.

Can be closed or possible improvement of error handling with wrong user/password ;-)

**Comment by apnex** [comment]
Hi vMarkus!
Yes this is a known and fairly common error as a result of incorrect credentials.
Glad you worked out it - though we can do better for auth handling.
I'm reopening this issue to serve as an action to improve auth error output.

**Comment by apnex** [comment]
Hi vMarkus!

I found some time this morning to address this - as of `vmw-cli` **1.2.1** I have added AUTH handing to the client.

You will now receive this error if either the VMWUSER or VMWPASS is incorrect:
`[ERROR]: 401 AUTH-ERROR please check environment variables $VMWUSER and $VMWPASS are correct!`
